#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamJam.RatingsSample.Droid.Resource", IsApplication=true)]

namespace XamJam.RatingsSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::XamJam.RatingsSample.Droid.Resource.Attribute.actionBarSize;
			global::XamSvg.Resource.Attribute.colorMapping = global::XamJam.RatingsSample.Droid.Resource.Attribute.colorMapping;
			global::XamSvg.Resource.Attribute.colorMappingSelected = global::XamJam.RatingsSample.Droid.Resource.Attribute.colorMappingSelected;
			global::XamSvg.Resource.Attribute.svg = global::XamJam.RatingsSample.Droid.Resource.Attribute.svg;
			global::XamSvg.Resource.Attribute.useCache = global::XamJam.RatingsSample.Droid.Resource.Attribute.useCache;
			global::XamSvg.Resource.Styleable.SvgImageView = global::XamJam.RatingsSample.Droid.Resource.Styleable.SvgImageView;
			global::XamSvg.Resource.Styleable.SvgImageView_colorMapping = global::XamJam.RatingsSample.Droid.Resource.Styleable.SvgImageView_colorMapping;
			global::XamSvg.Resource.Styleable.SvgImageView_colorMappingSelected = global::XamJam.RatingsSample.Droid.Resource.Styleable.SvgImageView_colorMappingSelected;
			global::XamSvg.Resource.Styleable.SvgImageView_svg = global::XamJam.RatingsSample.Droid.Resource.Styleable.SvgImageView_svg;
			global::XamSvg.Resource.Styleable.SvgImageView_useCache = global::XamJam.RatingsSample.Droid.Resource.Styleable.SvgImageView_useCache;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int colorMapping = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int colorMappingSelected = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int svg = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int useCache = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SvgImageView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int SvgImageView_colorMapping = 1;
			
			// aapt resource value: 2
			public const int SvgImageView_colorMappingSelected = 2;
			
			// aapt resource value: 0
			public const int SvgImageView_svg = 0;
			
			// aapt resource value: 3
			public const int SvgImageView_useCache = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
